L1 offchain register domain
blockful-io/external-resolver pull request #107
Opened 2024-06-04 18:21 UTC by pikonha

# L1 offchain register domain

## All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

## Description

## Related Issue

## Changes
- [ ] New feature implementation
- [ ] Bug fix
- [ ] Code refactoring
- [ ] Documentation update
- [ ] Other (please specify)

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

## Additional Notes

2024-06-05 20:27 UTC, LeonardoVieira1630 requested changes
Nice pull request Pik. I also run the tests here and every thing is fine.

2024-06-06 12:51 UTC, pikonha commented on packages/gateway/src/handlers/slots.ts
> +      if (addr === zeroAddress) {
`address(0)` is solidity syntax

2024-06-06 12:51 UTC, pikonha commented on packages/client/src/read.ts
> +  .option('-i --chainId <chainId>', 'chainId', '31337')
anvil's id is 31337

2024-06-06 12:52 UTC, pikonha commented on foundry.toml
> +ignored_warnings_from = [
ignore warnings from dependencies such as ens-contracts and openzepplein since we can't do anything about it

2024-06-06 13:14 UTC, pikonha commented on .vscode/launch.json
> +        "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318"
there's no way to pass an environment variable to the debug settings. this works just as a placeholder so you know where to put the locally deployed resolver

2024-06-07 11:36 UTC, merged