Gateway structure
blockful-io/external-resolver pull request #29
Opened 2024-03-01 13:39 UTC by LeonardoVieira1630

# Gateway structure

## All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

## Description

This pull request introduces a basic gateway structure to the project, developed based on ccip-read. Handlers for functions indicated by ENS interfaces have been implemented, providing an initial integration with it.

## Related Issue
#10 

## Changes
- [x] Gateway Structure: Added the basic gateway structure using ccip-read-server.
- [x] ENS Interfaces Handlers: Implemented handlers for functions indicated by ENS interfaces. The handlers respond to calls and perform specific operations as needed.
- [x] Test File: Introduced a test file to validate gateway calls.

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

2024-03-01 19:05 UTC, pikonha requested changes

2024-03-01 19:05 UTC, pikonha commented on packages/gateway/src/gateWay.ts
why to call it `gateWay`? perhaps `server` would be a more meaningful name for this file so then after we implement an `index.ts` file that initializes the server, db, and all the other components.

2024-03-01 19:58 UTC, LeonardoVieira1630 commented on packages/gateway/README.MD
> +yarn test
Nice! Will add that.

2024-03-01 20:00 UTC, LeonardoVieira1630 commented on packages/gateway/package.json
> +  "main": "index.js",
It was set by default as index.js. But yeah, it doesnt exist. I'll change it.

2024-03-01 20:02 UTC, LeonardoVieira1630 commented on packages/gateway/src/gateWay.ts
Got you, make sense. This file looks more like the "core" of the gateway. We can call it server, no problem.

2024-03-03 23:56 UTC, pikonha approved these changes
LGTM

2024-03-04 13:17 UTC, merged